/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package affichage;

import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import mapping.Employer;
import mapping.Poste;

/**
 *
 * @author mbola
 */
public class FenetrageListeEmploye extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    FenetrageDemandeConge demande_conge;
    public FenetrageListeEmploye(FenetrageDemandeConge fen) throws Exception {
        initComponents();
        this.demande_conge = fen;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() throws Exception {

        jLabel2 = new javax.swing.JLabel();
        titre = new javax.swing.JLabel();
        label_nom = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        label_poste = new javax.swing.JLabel();
        poste = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_employe = new javax.swing.JTable();
        bt_ajouter = new javax.swing.JButton();
        label_prenom = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titre.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        titre.setText("Liste Employe");

        label_nom.setText("Nom :  ");

        nom.addKeyListener(new java.awt.event.KeyListener() {
            public void keyUp(java.awt.event.KeyEvent evt) {
                
            }

            @Override
            public void keyTyped(KeyEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void keyReleased(KeyEvent e) {
                nomKeyUp(e);
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void keyPressed(KeyEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });

        label_poste.setText("Poste : ");

        poste.setModel(new javax.swing.DefaultComboBoxModel(Poste.getListPoste()));
        poste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posteActionPerformed(evt);
            }
        });

        table_employe.setModel(new javax.swing.table.DefaultTableModel(
            Employer.liste_employe(nom.getText(), prenom.getText(), poste.getSelectedItem().toString()),
            new String [] {
                "Matricule", "Cin", "Nom", "Prénom"
            }
        ));
        jScrollPane1.setViewportView(table_employe);

        bt_ajouter.setText("Ajouter");
        bt_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ajouterActionPerformed(evt);
            }
        });

        label_prenom.setText("Prénom : ");

        prenom.addKeyListener(new java.awt.event.KeyListener() {
            public void keyUp(java.awt.event.KeyEvent evt) {
                
            }

            @Override
            public void keyTyped(KeyEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void keyReleased(KeyEvent e) {
                prenomKeyUp(e);
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void keyPressed(KeyEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(titre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_nom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_prenom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_poste)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(poste, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bt_ajouter)
                .addGap(392, 392, 392))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titre)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nom)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_poste)
                    .addComponent(poste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_prenom)
                    .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_ajouter)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void nomKeyUp(java.awt.event.KeyEvent evt) {                             
        try {
            table_employe.setModel(new javax.swing.table.DefaultTableModel(
            Employer.liste_employe(nom.getText(), prenom.getText(), poste.getSelectedItem().toString()),
            new String [] {
                "Matricule", "Cin", "Nom", "Prénom"
            }
        ));
                    } catch (Exception ex) {
            Logger.getLogger(FenetrageListeEmploye.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                            

    private void posteActionPerformed(java.awt.event.ActionEvent evt) {                                      
        try {
            table_employe.setModel(new javax.swing.table.DefaultTableModel(
            Employer.liste_employe(nom.getText(), prenom.getText(), poste.getSelectedItem().toString()),
            new String [] {
                "Matricule", "Cin", "Nom", "Prénom"
            }
        ));
                    } catch (Exception ex) {
            Logger.getLogger(FenetrageListeEmploye.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                     

    private void bt_ajouterActionPerformed(java.awt.event.ActionEvent evt) {                                           
        int matricule = table_employe.getSelectedRow();
        demande_conge.getNum_matricule().setText(table_employe.getValueAt(matricule, 0).toString());
        this.dispose();
    }                                          

    private void prenomKeyUp(java.awt.event.KeyEvent evt) {                                
        try {
            table_employe.setModel(new javax.swing.table.DefaultTableModel(
            Employer.liste_employe(nom.getText(), prenom.getText(), poste.getSelectedItem().toString()),
            new String [] {
                "Matricule", "Cin", "Nom", "Prénom"
            }
        ));
                    } catch (Exception ex) {
            Logger.getLogger(FenetrageListeEmploye.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                               

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JButton bt_ajouter;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_nom;
    private javax.swing.JLabel label_poste;
    private javax.swing.JLabel label_prenom;
    private javax.swing.JTextField nom;
    private javax.swing.JComboBox poste;
    private javax.swing.JTextField prenom;
    private javax.swing.JTable table_employe;
    private javax.swing.JLabel titre;
    // End of variables declaration                   
}
