/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package affichage;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author mbola
 */
public class FenetrageDemandeConge extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public FenetrageDemandeConge() {
        initComponents();
    }

    public JButton getBt_enregistrer() {
        return bt_enregistrer;
    }

    public void setBt_enregistrer(JButton bt_enregistrer) {
        this.bt_enregistrer = bt_enregistrer;
    }

    public JButton getBt_liste_employe() {
        return bt_liste_employe;
    }

    public void setBt_liste_employe(JButton bt_liste_employe) {
        this.bt_liste_employe = bt_liste_employe;
    }

    public JTextField getDt_depart() {
        return dt_depart;
    }

    public void setDt_depart(JTextField dt_depart) {
        this.dt_depart = dt_depart;
    }

    public JTextField getDt_retour() {
        return dt_retour;
    }

    public void setDt_retour(JTextField dt_retour) {
        this.dt_retour = dt_retour;
    }

    public JTextField getDt_saisie() {
        return dt_saisie;
    }

    public void setDt_saisie(JTextField dt_saisie) {
        this.dt_saisie = dt_saisie;
    }

    public JTextField getHeure_depart() {
        return heure_depart;
    }

    public void setHeure_depart(JTextField heure_depart) {
        this.heure_depart = heure_depart;
    }

    public JTextField getHeure_retour() {
        return heure_retour;
    }

    public void setHeure_retour(JTextField heure_retour) {
        this.heure_retour = heure_retour;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLabel_dt_depart() {
        return label_dt_depart;
    }

    public void setLabel_dt_depart(JLabel label_dt_depart) {
        this.label_dt_depart = label_dt_depart;
    }

    public JLabel getLabel_dt_retour() {
        return label_dt_retour;
    }

    public void setLabel_dt_retour(JLabel label_dt_retour) {
        this.label_dt_retour = label_dt_retour;
    }

    public JLabel getLabel_dt_saisie() {
        return label_dt_saisie;
    }

    public void setLabel_dt_saisie(JLabel label_dt_saisie) {
        this.label_dt_saisie = label_dt_saisie;
    }

    public JLabel getLabel_heure_depart() {
        return label_heure_depart;
    }

    public void setLabel_heure_depart(JLabel label_heure_depart) {
        this.label_heure_depart = label_heure_depart;
    }

    public JLabel getLabel_heure_retour() {
        return label_heure_retour;
    }

    public void setLabel_heure_retour(JLabel label_heure_retour) {
        this.label_heure_retour = label_heure_retour;
    }

    public JLabel getLabel_motif() {
        return label_motif;
    }

    public void setLabel_motif(JLabel label_motif) {
        this.label_motif = label_motif;
    }

    public JLabel getLabel_num_matricule() {
        return label_num_matricule;
    }

    public void setLabel_num_matricule(JLabel label_num_matricule) {
        this.label_num_matricule = label_num_matricule;
    }

    public JTextArea getMotif() {
        return motif;
    }

    public void setMotif(JTextArea motif) {
        this.motif = motif;
    }

    public JTextField getNum_matricule() {
        return num_matricule;
    }

    public void setNum_matricule(JTextField num_matricule) {
        this.num_matricule = num_matricule;
    }

    public JLabel getTitre() {
        return titre;
    }

    public void setTitre(JLabel titre) {
        this.titre = titre;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        titre = new javax.swing.JLabel();
        label_num_matricule = new javax.swing.JLabel();
        num_matricule = new javax.swing.JTextField();
        bt_liste_employe = new javax.swing.JButton();
        label_dt_saisie = new javax.swing.JLabel();
        dt_saisie = new javax.swing.JTextField();
        label_motif = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        motif = new javax.swing.JTextArea();
        label_dt_depart = new javax.swing.JLabel();
        dt_depart = new javax.swing.JTextField();
        label_heure_depart = new javax.swing.JLabel();
        heure_depart = new javax.swing.JTextField();
        label_dt_retour = new javax.swing.JLabel();
        dt_retour = new javax.swing.JTextField();
        label_heure_retour = new javax.swing.JLabel();
        heure_retour = new javax.swing.JTextField();
        bt_enregistrer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titre.setText("DEMANDE DE CONGE");

        label_num_matricule.setText("Numéro Matricule : ");

        bt_liste_employe.setText("Liste Employe");
        bt_liste_employe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_liste_employeActionPerformed(evt);
            }
        });

        label_dt_saisie.setText("Date saisie demande : ");

        label_motif.setText("Motif demande : ");

        motif.setColumns(20);
        motif.setRows(5);
        jScrollPane1.setViewportView(motif);

        label_dt_depart.setText("Date départ : ");

        label_heure_depart.setText("Heure départ : ");

        label_dt_retour.setText("Date retour : ");

        label_heure_retour.setText("Heure retour :");

        heure_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heure_retourActionPerformed(evt);
            }
        });

        bt_enregistrer.setText("Enregistrer");
        bt_enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enregistrerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titre)
                .addGap(235, 235, 235))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_dt_saisie)
                    .addComponent(label_num_matricule)
                    .addComponent(label_motif)
                    .addComponent(label_dt_depart)
                    .addComponent(label_dt_retour))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dt_saisie, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(num_matricule))
                        .addGap(34, 34, 34)
                        .addComponent(bt_liste_employe))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dt_depart, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dt_retour, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label_heure_depart)
                                .addComponent(label_heure_retour))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(heure_retour, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                .addComponent(heure_depart))))
                    .addComponent(bt_enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(titre)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_num_matricule)
                    .addComponent(num_matricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_liste_employe))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_dt_saisie)
                    .addComponent(dt_saisie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_motif)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_dt_depart)
                    .addComponent(dt_depart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_heure_depart)
                    .addComponent(heure_depart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_dt_retour)
                    .addComponent(dt_retour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_heure_retour)
                    .addComponent(heure_retour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(bt_enregistrer)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>                        

    private void heure_retourActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void bt_liste_employeActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        try {
            new FenetrageListeEmploye(this).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FenetrageDemandeConge.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                                

    private void bt_enregistrerActionPerformed(java.awt.event.ActionEvent evt) {                                               
        
    }                                              

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JButton bt_enregistrer;
    private javax.swing.JButton bt_liste_employe;
    private javax.swing.JTextField dt_depart;
    private javax.swing.JTextField dt_retour;
    private javax.swing.JTextField dt_saisie;
    private javax.swing.JTextField heure_depart;
    private javax.swing.JTextField heure_retour;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_dt_depart;
    private javax.swing.JLabel label_dt_retour;
    private javax.swing.JLabel label_dt_saisie;
    private javax.swing.JLabel label_heure_depart;
    private javax.swing.JLabel label_heure_retour;
    private javax.swing.JLabel label_motif;
    private javax.swing.JLabel label_num_matricule;
    private javax.swing.JTextArea motif;
    private javax.swing.JTextField num_matricule;
    private javax.swing.JLabel titre;
    // End of variables declaration                   
}
