/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package affichage;

import java.util.logging.Level;
import java.util.logging.Logger;
import mapping.Employer;
import mapping.Entree_poste_service;
import mapping.Horaire;
import mapping.Poste;
import mapping.Service;

/**
 *
 * @author mbola
 */
public class FenetrageEmployer extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public FenetrageEmployer() throws Exception {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() throws Exception {

        titre = new javax.swing.JLabel();
        label_nom = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        label_prenom = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();
        label_cin = new javax.swing.JLabel();
        cin = new javax.swing.JTextField();
        label_dtn = new javax.swing.JLabel();
        dtn = new javax.swing.JTextField();
        label_sexe = new javax.swing.JLabel();
        sexe = new javax.swing.JComboBox();
        label_dt_embauche = new javax.swing.JLabel();
        dt_embauche = new javax.swing.JTextField();
        label_poste = new javax.swing.JLabel();
        poste = new javax.swing.JComboBox();
        label_service = new javax.swing.JLabel();
        service = new javax.swing.JComboBox();
        label_liste_employe = new javax.swing.JLabel();
        label_heure_entree = new javax.swing.JLabel();
        heure_entree = new javax.swing.JTextField();
        label_heure_sortie = new javax.swing.JLabel();
        heure_sortie = new javax.swing.JTextField();
        label_heure_debut_pause = new javax.swing.JLabel();
        heure_debut_pause = new javax.swing.JTextField();
        label_heure_fin_pause = new javax.swing.JLabel();
        heure_fin_pause = new javax.swing.JTextField();
        bt_enregistrer = new javax.swing.JButton();
        label_heure_travail1 = new javax.swing.JLabel();
        bt_actualiser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titre.setText("AJOUT ET LISTE EMPLOYE");

        label_nom.setText("Nom : ");

        label_prenom.setText("Prénom : ");

        label_cin.setText("CIN : ");

        label_dtn.setText("Date de naissance : ");

        label_sexe.setText("Sexe : ");

        sexe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculin", "Feminin" }));
        sexe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexeActionPerformed(evt);
            }
        });

        label_dt_embauche.setText("Date d'embauche : ");

        label_poste.setText("Poste : ");

        poste.setModel(new javax.swing.DefaultComboBoxModel(Poste.getListPoste()));

        label_service.setText("Service : ");

        service.setModel(new javax.swing.DefaultComboBoxModel(Service.getListService()));

        label_liste_employe.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label_liste_employe.setText("Liste de tous les employés :");

        label_heure_entree.setText("Heure d'entrée : ");

        label_heure_sortie.setText("Heure de sortie : ");

        label_heure_debut_pause.setText("Heure debut pause : ");

        label_heure_fin_pause.setText("Heure fin pause : ");

        bt_enregistrer.setText("Enregistrer l'employé avec son horaire");
        bt_enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enregistrerActionPerformed(evt);
            }
        });

        label_heure_travail1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label_heure_travail1.setText("Heure de travail : ");

        bt_actualiser.setText("Actualiser");
        bt_actualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_actualiserActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Num*Matricule", "Num*CIN", "Nom", "Prénom", "Poste", "Service"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(4).setResizable(false);
            table.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_heure_travail1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label_sexe)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sexe, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label_nom)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(label_dt_embauche)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dt_embauche, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(label_poste)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(poste, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(54, 54, 54)
                                        .addComponent(label_service)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(service, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(label_prenom)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(titre)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(label_cin)
                                                .addGap(29, 29, 29)
                                                .addComponent(cin, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(54, 54, 54)
                                                .addComponent(label_dtn)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dtn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_liste_employe)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label_heure_entree)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(heure_entree, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(label_heure_sortie)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(heure_sortie, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(label_heure_debut_pause)
                                        .addGap(29, 29, 29)
                                        .addComponent(heure_debut_pause, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                        .addComponent(label_heure_fin_pause)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(heure_fin_pause, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bt_enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bt_actualiser))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nom)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_prenom)
                    .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_cin)
                    .addComponent(cin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_dtn)
                    .addComponent(dtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_sexe)
                    .addComponent(sexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_dt_embauche)
                    .addComponent(dt_embauche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_poste)
                    .addComponent(poste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_service)
                    .addComponent(service, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(label_heure_travail1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_heure_entree)
                    .addComponent(heure_entree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_heure_sortie)
                    .addComponent(heure_sortie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_heure_debut_pause)
                    .addComponent(heure_debut_pause, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_heure_fin_pause)
                    .addComponent(heure_fin_pause, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(bt_enregistrer)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_liste_employe)
                    .addComponent(bt_actualiser))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>                        

    private void sexeActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void bt_enregistrerActionPerformed(java.awt.event.ActionEvent evt) {                                               
        try {
            Employer emp = new Employer(Employer.getIdEmployer(),cin.getText(),jTextField1.getText(),prenom.getText(),sexe.getSelectedItem().toString(),dtn.getText(),dt_embauche.getText());
            Entree_poste_service poste_service = new Entree_poste_service(Entree_poste_service.getIdEntree_poste_service(),emp.getID_EMPLOYER(),Poste.getPosteByNom(poste.getSelectedItem().toString()).getID_POSTE(),Service.getServiceByNom(service.getSelectedItem().toString()).getID_SERVICE(),dt_embauche.getText());
            Horaire horaire = new Horaire(Horaire.getIdHoraire(),emp.getID_EMPLOYER(),heure_entree.getText(),heure_sortie.getText(),heure_debut_pause.getText(),heure_fin_pause.getText());
            System.out.println(emp.setEmployer());
            System.out.println(poste_service.setEntre_poste_service());
            System.out.println(horaire.setHoraire());
        } catch (Exception ex) {
            Logger.getLogger(FenetrageEmployer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                              

    private void bt_actualiserActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JButton bt_actualiser;
    private javax.swing.JButton bt_enregistrer;
    private javax.swing.JTextField cin;
    private javax.swing.JTextField dt_embauche;
    private javax.swing.JTextField dtn;
    private javax.swing.JTextField heure_debut_pause;
    private javax.swing.JTextField heure_entree;
    private javax.swing.JTextField heure_fin_pause;
    private javax.swing.JTextField heure_sortie;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label_cin;
    private javax.swing.JLabel label_dt_embauche;
    private javax.swing.JLabel label_dtn;
    private javax.swing.JLabel label_heure_debut_pause;
    private javax.swing.JLabel label_heure_entree;
    private javax.swing.JLabel label_heure_fin_pause;
    private javax.swing.JLabel label_heure_sortie;
    private javax.swing.JLabel label_heure_travail1;
    private javax.swing.JLabel label_liste_employe;
    private javax.swing.JLabel label_nom;
    private javax.swing.JLabel label_poste;
    private javax.swing.JLabel label_prenom;
    private javax.swing.JLabel label_service;
    private javax.swing.JLabel label_sexe;
    private javax.swing.JComboBox poste;
    private javax.swing.JTextField prenom;
    private javax.swing.JComboBox service;
    private javax.swing.JComboBox sexe;
    private javax.swing.JTable table;
    private javax.swing.JLabel titre;
    // End of variables declaration                   
}
